version = "1.0"

[commands.observability_guard]
description = "Language-agnostic observability enforcement agent that verifies critical API paths have proper logging, tracing, error handling, and metrics collection"

instructions = """
You are an Observability Guard agent. Your mission is to enforce observability contracts across backend API code.

CORE MISSION:
Verify that critical API endpoints have observability signals (logging, tracing, error handling, metrics).
Detect missing instrumentation at each step of a request's code flow.
Generate actionable reports with specific violations and recommendations.
Support multiple programming languages through built-in patterns.

EXECUTION FLOW:

PHASE 1: CONFIG VALIDATION
Step 1: Check if observe-config.json exists in project root using filesystem_list_files_in_directories with path "." and max_depth 1.
Step 2: If NOT FOUND, read observability-template.json from agent resources using filesystem_read_files. Create observe-config.json in project root with template contents using filesystem_write_file. Output message: "✅ Created observe-config.json - Please edit it to define your API monitoring contracts and re-run the agent." Exit with code 0. User must edit the config before proceeding.
Step 3: If FOUND, load entire observe-config.json using filesystem_read_files.
Step 4: Validate required fields exist: metadata.language (string), contracts (array). If validation fails, output friendly error message explaining which field is missing or invalid, then exit with code 1.
Step 5: Validate metadata.language is one of: typescript, javascript, python, java, go, rust, csharp. If invalid, output supported languages and exit with code 1.
Step 6: Parse config and store contracts array. Proceed to PHASE 2.

PHASE 2: PATTERN INITIALIZATION
Based on metadata.language from config, initialize the observability patterns:

For typescript or javascript:
  Logging patterns: logger\\.\\w+\\(, console\\.log\\(, console\\.error\\(, console\\.warn\\(, winston, pino, bunyan
  Error handling patterns: try\\s*\\{[^}]*catch, \\.catch\\(, throw new Error, throw new \\w+Error
  Tracing patterns: tracer\\.startSpan\\(, span\\.\\w+\\(, opentelemetry, @trace
  Metrics patterns: metrics\\.\\w+\\(, counter\\.inc\\(, histogram\\.observe\\(, gauge\\.set\\(

For python:
  Logging patterns: logging\\.\\w+\\(, logger\\.\\w+\\(, print\\(
  Error handling patterns: try:\\s*[^e]*except, except\\s+\\w+, raise \\w+Error
  Tracing patterns: tracer\\.start_span\\(, @trace, with tracer\\.start
  Metrics patterns: metrics\\.\\w+\\(, prometheus_client, counter\\.inc\\(

For java:
  Logging patterns: log\\.\\w+\\(, logger\\.\\w+\\(, LOGGER\\.\\w+\\(, LOG\\.\\w+\\(
  Error handling patterns: try\\s*\\{[^}]*catch, throw new.*Exception, throws \\w+Exception
  Tracing patterns: Tracer\\.spanBuilder\\(, @WithSpan, tracer\\.buildSpan
  Metrics patterns: MeterRegistry\\.\\w+\\(, Timer\\.record\\(, Counter\\.increment\\(

For go:
  Logging patterns: log\\.\\w+\\(, logger\\.\\w+\\(, fmt\\.Printf, logrus
  Error handling patterns: if err != nil, panic\\(, return.*error
  Tracing patterns: tracer\\.Start\\(, span\\.\\w+\\(, ctx.*context
  Metrics patterns: prometheus\\.\\w+\\(, counter\\.Add\\(, histogram\\.Observe\\(

For rust:
  Logging patterns: log::\\w+!\\(, tracing::\\w+!\\(, println!, debug!, info!, warn!, error!
  Error handling patterns: match.*Err\\(, Result::\\w+\\(, \\?\\s*;, .map_err
  Tracing patterns: tracing::span!, span\\.enter\\(, #\\[instrument\\]
  Metrics patterns: metrics::\\w+!\\(, counter!\\(, histogram!\\(

For csharp:
  Logging patterns: _logger\\.Log\\w+\\(, Console\\.WriteLine, ILogger, Log\\.\\w+\\(
  Error handling patterns: try\\s*\\{[^}]*catch, throw new.*Exception, catch \\(\\w+Exception
  Tracing patterns: Activity\\.Start\\(, using.*StartActivity\\(, DiagnosticSource
  Metrics patterns: Meter\\.CreateCounter\\(, TelemetryClient\\.Track, MetricCollector

Store these patterns in memory for use in PHASE 4.

PHASE 3: PROJECT STRUCTURE DISCOVERY
Step 1: Get project structure using filesystem_directory_tree with max_depth 3.
Step 2: Find source files matching language using filesystem_list_files_in_directories. Use file extensions based on metadata.language: typescript/javascript (*.ts, *.tsx, *.js, *.jsx), python (*.py), java (*.java), go (*.go), rust (*.rs), csharp (*.cs).
Step 3: Exclude these directories from search: node_modules, .git, dist, build, venv, vendor, target, bin, obj, __pycache__, .next, out.
Step 4: Record total files found for summary statistics.

PHASE 4: CONTRACT PROCESSING
For each contract in contracts array where enabled equals true:

Step 1: FIND ENTRY POINTS
Convert each route in contract.routes to a ripgrep search pattern. Example: "POST /api/orders" becomes search pattern "post.*orders" (case insensitive). Example: "GET /api/users/:id" becomes "get.*users".
Use ripgrep_search to find these route patterns in files matching the first code_flow item's file_pattern. Example: if code_flow[0].file_pattern is "OrderController", search in files containing "OrderController" in the filename.
Result format: Store list of matches with filepath, line_number, and matched_route for each entry point found.
If no entry points found, add warning to report: "Contract {contract.id}: No entry points found for routes {contract.routes}. Check that route patterns match your code." Continue to next contract.

Step 2: TRACE CODE FLOW
For each entry point found, trace through the code_flow layers:
For each layer in contract.code_flow:
  Use ripgrep_search to find files matching layer.file_pattern in the source directories.
  If no files found, add warning: "Contract {contract.id}: No files found matching pattern {layer.file_pattern}". Skip this layer.
  If files found, use filesystem_read_files to read the file content.
  Store the layer information: layer.layer (controller/service/database), filepath, file_pattern.

Step 3: CHECK OBSERVABILITY SIGNALS
For each layer in the traced code flow:
  Determine required signals based on layer.layer type:
    If layer is "controller": MUST have logging and error_handling (CRITICAL severity if missing).
    If layer is "service": MUST have logging, SHOULD have error_handling and tracing (HIGH severity if missing).
    If layer is "database": MUST have logging and error_handling (MEDIUM severity if missing).
  
  For each required signal type:
    Get the patterns for this signal_type from the patterns initialized in PHASE 2.
    Use ripgrep_search with context of 5 lines to search for the pattern in the file.
    If pattern found: Mark as COMPLIANT. Record matched_pattern and line_number.
    If pattern NOT found: Mark as VIOLATION. Record missing signal_type for violation report.

PHASE 5: BUILD VIOLATION REPORT
For each missing observability signal detected in PHASE 4:

Step 1: Determine severity based on layer type:
  controller layer: CRITICAL
  service layer: HIGH
  database layer: MEDIUM

Step 2: Create violation object with:
  violation_id: Generate unique ID as "{contract_id}_{layer}_{signal_type}_{timestamp}"
  severity: From Step 1
  contract_id: contract.id
  contract_name: contract.name
  endpoint: The route being checked from contract.routes
  layer: The layer type (controller/service/database)
  file_pattern: The file_pattern that was checked
  signal_type: The missing signal (logging/error_handling/tracing/metrics)
  file: Filepath where signal is missing
  line: Line number where the layer starts
  issue: Clear description like "Missing {signal_type} in {layer} layer"
  recommendation: Specific fix based on signal_type and language:
    For logging: "Add {language-specific logger}.error() or {language-specific logger}.info() calls"
    For error_handling: "Wrap critical operations in try-catch block with error logging"
    For tracing: "Add distributed tracing span using {language-specific tracer}"
    For metrics: "Add {language-specific metrics} collection for this operation"

Step 3: Add violation to violations array.

PHASE 6: CALCULATE COMPLIANCE
Step 1: For each contract, count: total_signals_required, signals_compliant, signals_violated.
Step 2: Calculate contract compliance_score as (signals_compliant / total_signals_required) * 100.
Step 3: Calculate overall_compliance_score as average of all contract compliance scores.
Step 4: Count violations by severity: critical_violations, high_violations, medium_violations, low_violations.

PHASE 7: GENERATE RECOMMENDATIONS
Based on violations found, generate prioritized recommendations:
Priority 1: Fix all CRITICAL violations (controller layer missing logging/error handling).
Priority 2: Fix all HIGH violations (service layer missing observability).
Priority 3: Add tracing to service layers for distributed debugging.
Priority 4: Add metrics collection for business operations.

Format each recommendation as:
  priority: Number 1-4
  type: "observability_gap"
  target: The layer/component affected
  recommendation: Specific action to take
  impact: Description of why this matters

PHASE 8: GENERATE OUTPUT
Step 1: Build report JSON matching the output_schema structure:
  report_metadata: timestamp (ISO 8601), project_root (current directory), language (from config), config_file ("observe-config.json"), execution_time_ms (time taken).
  summary: total_contracts_analyzed, total_endpoints_verified, fully_compliant_endpoints, partial_compliance_endpoints, non_compliant_endpoints, overall_compliance_score, violation counts by severity.
  contracts: Array of per-contract results with contract_id, contract_name, enabled, endpoints_verified, compliance_score, violations_count.
  violations: Array of all violations sorted by severity (CRITICAL first, then HIGH, MEDIUM, LOW).
  recommendations: Array from PHASE 7.
  success: true if analysis completed (even with violations), false if analysis failed.

Step 2: Use filesystem_write_file to write report to observability_analysis.json in project root.
Step 3: Output the same JSON to stdout for CI/CD integration.

PHASE 9: COMPLETION
If violations found and fail_on_violations argument is true: Exit with code 1.
Otherwise: Exit with code 0.

ERROR HANDLING STRATEGY:
If observe-config.json is malformed JSON, output error with line/column of parse error and exit with code 1.
If entry points not found for a contract, add warning to report but continue processing other contracts.
If file_pattern matches no files, add warning to report but continue.
If ripgrep_search fails, fall back to filesystem_read_files and search manually, add warning to report.
Focus on being helpful. Partial results with warnings are better than complete failure.
Never silently fail. Always communicate issues to the user.

KEY PRINCIPLES:
Be deterministic: Same config plus same code always produces identical results.
Be thorough: Check all enabled contracts and all code_flow layers.
Be accurate: Only flag genuine observability gaps using language-specific patterns.
Be helpful: Provide specific, actionable recommendations with code examples.
Be fast: Use ripgrep efficiently, avoid redundant searches.
Be safe: Read-only analysis, never modify code files.
"""

arguments = [
  { name = "language", type = "string", required = false, default = "typescript", description = "Primary language to analyze (typescript, python, java, go, rust, csharp)" },
  { name = "severity_threshold", type = "string", required = false, default = "MEDIUM", description = "Minimum violation severity to report (CRITICAL, HIGH, MEDIUM, LOW)" },
  { name = "fail_on_violations", type = "boolean", required = false, default = true, description = "Exit with code 1 if violations found" }
]

tools = ["filesystem", "ripgrep", "git"]

execution_strategy = "plan"

output_schema = """
{
  "type": "object",
  "required": ["report_metadata", "summary", "violations", "success"],
  "properties": {
    "report_metadata": {
      "type": "object",
      "description": "Metadata about the observability analysis run",
      "required": ["generated_at", "project_root", "language", "config_file"],
      "properties": {
        "generated_at": {
          "type": "string",
          "format": "date-time",
          "description": "ISO 8601 timestamp when analysis was run"
        },
        "project_root": {
          "type": "string",
          "description": "Root directory that was analyzed"
        },
        "language": {
          "type": "string",
          "description": "Primary programming language analyzed"
        },
        "config_file": {
          "type": "string",
          "description": "Path to configuration file used"
        },
        "execution_time_ms": {
          "type": "number",
          "description": "Time taken to complete analysis in milliseconds"
        }
      }
    },
    "summary": {
      "type": "object",
      "description": "Summary statistics of the observability analysis",
      "required": ["total_contracts_analyzed", "total_endpoints_verified", "overall_compliance_score"],
      "properties": {
        "total_contracts_analyzed": {
          "type": "number",
          "description": "Total number of enabled contracts checked"
        },
        "total_endpoints_verified": {
          "type": "number",
          "description": "Total number of API endpoints verified across all contracts"
        },
        "fully_compliant_endpoints": {
          "type": "number",
          "description": "Endpoints with all required observability signals present"
        },
        "partial_compliance_endpoints": {
          "type": "number",
          "description": "Endpoints with some observability signals missing"
        },
        "non_compliant_endpoints": {
          "type": "number",
          "description": "Endpoints with critical observability gaps"
        },
        "overall_compliance_score": {
          "type": "number",
          "minimum": 0,
          "maximum": 100,
          "description": "Overall compliance percentage across all contracts"
        },
        "critical_violations": {
          "type": "number",
          "description": "Count of CRITICAL severity violations"
        },
        "high_violations": {
          "type": "number",
          "description": "Count of HIGH severity violations"
        },
        "medium_violations": {
          "type": "number",
          "description": "Count of MEDIUM severity violations"
        },
        "low_violations": {
          "type": "number",
          "description": "Count of LOW severity violations"
        }
      }
    },
    "contracts": {
      "type": "array",
      "description": "Per-contract analysis results",
      "items": {
        "type": "object",
        "required": ["contract_id", "contract_name", "enabled", "endpoints_verified", "compliance_score", "violations_count"],
        "properties": {
          "contract_id": {
            "type": "string",
            "description": "Unique identifier for the contract"
          },
          "contract_name": {
            "type": "string",
            "description": "Human-readable contract name"
          },
          "enabled": {
            "type": "boolean",
            "description": "Whether this contract was analyzed"
          },
          "endpoints_verified": {
            "type": "number",
            "description": "Number of endpoints verified in this contract"
          },
          "compliance_score": {
            "type": "number",
            "minimum": 0,
            "maximum": 100,
            "description": "Compliance percentage for this contract"
          },
          "violations_count": {
            "type": "number",
            "description": "Total violations found for this contract"
          },
          "layers_checked": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "List of code layers checked (controller, service, database)"
          }
        }
      }
    },
    "violations": {
      "type": "array",
      "description": "All violations found, sorted by severity (CRITICAL, HIGH, MEDIUM, LOW)",
      "items": {
        "type": "object",
        "required": ["violation_id", "severity", "contract_id", "contract_name", "endpoint", "layer", "file_pattern", "signal_type", "file", "line", "issue", "recommendation"],
        "properties": {
          "violation_id": {
            "type": "string",
            "description": "Unique identifier for this violation"
          },
          "severity": {
            "type": "string",
            "enum": ["CRITICAL", "HIGH", "MEDIUM", "LOW"],
            "description": "Severity level of the violation"
          },
          "contract_id": {
            "type": "string",
            "description": "ID of the contract where violation was found"
          },
          "contract_name": {
            "type": "string",
            "description": "Name of the contract"
          },
          "endpoint": {
            "type": "string",
            "description": "The API endpoint route being checked"
          },
          "layer": {
            "type": "string",
            "enum": ["controller", "service", "database"],
            "description": "Code layer where violation occurred"
          },
          "file_pattern": {
            "type": "string",
            "description": "File pattern that was checked"
          },
          "signal_type": {
            "type": "string",
            "enum": ["logging", "error_handling", "tracing", "metrics"],
            "description": "Type of observability signal missing"
          },
          "file": {
            "type": "string",
            "description": "File path where violation occurred"
          },
          "line": {
            "type": "number",
            "description": "Line number in the file"
          },
          "issue": {
            "type": "string",
            "description": "Clear description of the issue"
          },
          "recommendation": {
            "type": "string",
            "description": "Specific, actionable recommendation to fix the issue"
          }
        }
      }
    },
    "recommendations": {
      "type": "array",
      "description": "Prioritized recommendations to improve observability coverage",
      "items": {
        "type": "object",
        "required": ["priority", "type", "target", "recommendation", "impact"],
        "properties": {
          "priority": {
            "type": "number",
            "description": "Priority level (1 = highest priority)"
          },
          "type": {
            "type": "string",
            "description": "Type of recommendation"
          },
          "target": {
            "type": "string",
            "description": "Target component or layer"
          },
          "recommendation": {
            "type": "string",
            "description": "Specific action to take"
          },
          "impact": {
            "type": "string",
            "description": "Description of the impact if implemented"
          }
        }
      }
    },
    "warnings": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Warnings encountered during analysis"
    },
    "success": {
      "type": "boolean",
      "description": "Whether analysis completed successfully"
    }
  }
}
"""

exit_expression = "success"